### ISSUE TITLE
Ability to serialize entity without recursion.

### ISSUE THREAD

**Issue by Keeo** [UniqueLibs/ember-data-serializer-bundle#1]
How would you handle task when you need to serialize something without recursion? Just "here is entity(or array full of same entities) and give me json" kind of task. I think that serializer service should be also able to handle this task. What would you think about pullrequest?

**Comment by UniqueLibs** [comment]
You are able to define in every adapter which properties will be loaded recursive. But maybe i do not understand your question, so can you give me an example?

**Comment by Keeo** [comment]
I wrote this issue when I was not aware how this serializer works and was expecting it to behave similarly to  [jms](http://jmsyst.com/bundles/JMSSerializerBundle). It is not relevant anymore and as you said - its enough to set it in adapter.
